project:
  type: website
  output-dir: docs

website:
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - data_bytes.qmd
      - data_recipe.qmd
      - our-team.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



