project:
  type: website
  output-dir: docs

website:
  title: "NCEAS Coding Club"
  navbar:
    pinned: true
    background: primary
    left:
      - href: data_bytes.qmd
        text: Data Bytes
      - data_recipe.qmd
      - our-team.qmd
    right: 
      - icon: github
        href: https://github.com/nceas-coding-club/nceas-coding-club.github.io

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



