project:
  type: website
  output-dir: docs

website:
  navbar:
    pinned: true
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: data_bytes.qmd
        text: Data Bytes
      - data_recipe.qmd
      - our-team.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



