project:
  type: website
  output-dir: docs

website:
  title: "NCEAS Data Science Chats"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - our-team.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



